# Generated by Django 2.2.5 on 2019-10-07 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_reportkind_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoKind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=50, null=True)),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='reporttype',
            name='kind',
        ),
        migrations.AddField(
            model_name='reporttype',
            name='into_kind',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ReportKind'),
        ),
    ]
