# Generated by Django 2.2.5 on 2019-10-07 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20191007_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporttype',
            name='into_kind',
        ),
        migrations.AddField(
            model_name='reporttype',
            name='kind',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='reporttype',
            name='report_kind',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ReportKind'),
        ),
        migrations.CreateModel(
            name='InfoType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=1000, null=True, unique=True)),
                ('url', models.CharField(blank=True, max_length=1000, null=True)),
                ('url_web', models.CharField(blank=True, max_length=1000, null=True)),
                ('crtime', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('vendor', models.CharField(blank=True, max_length=50, null=True)),
                ('into_kind', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ReportKind')),
            ],
        ),
    ]
