# Generated by Django 2.2.5 on 2019-10-07 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20191007_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infotype',
            name='into_kind',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.InfoKind'),
        ),
    ]
