# Generated by Django 2.2.5 on 2019-10-07 14:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20191007_1102'),
    ]

    operations = [
        migrations.CreateModel(
            name='ASnum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asnum', models.CharField(blank=True, max_length=1000, null=True, unique=True)),
                ('region', models.CharField(blank=True, max_length=1000, null=True)),
                ('regionid', models.CharField(blank=True, max_length=200, null=True)),
                ('regionname', models.CharField(blank=True, max_length=1000, null=True)),
                ('astype', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('hostname', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('region', models.CharField(blank=True, max_length=200, null=True)),
                ('regionid', models.CharField(blank=True, max_length=200, null=True)),
                ('mr', models.CharField(blank=True, max_length=200, null=True)),
                ('modeltype', models.CharField(blank=True, max_length=200, null=True)),
                ('softver', models.CharField(blank=True, max_length=200, null=True)),
                ('latitude', models.CharField(blank=True, max_length=200, null=True)),
                ('longitude', models.CharField(blank=True, max_length=200, null=True)),
                ('pub_date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('igp_routes', models.PositiveIntegerField(blank=True, null=True)),
                ('vpnv4_routes', models.PositiveIntegerField(blank=True, null=True)),
                ('asnum', models.ManyToManyField(to='core.ASnum')),
            ],
        ),
    ]
