# Generated by Django 2.2.5 on 2019-10-09 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_asnum_device'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infotype',
            old_name='url_web',
            new_name='url_name',
        ),
        migrations.RenameField(
            model_name='reporttype',
            old_name='url_web',
            new_name='url_name',
        ),
        migrations.AddField(
            model_name='infokind',
            name='url_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='reportkind',
            name='url_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
