# Generated by Django 2.2.5 on 2019-09-26 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('senddata', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='date',
            new_name='start_date',
        ),
    ]
